### ISSUE TITLE
Making new workspace:  confusing error message about name constraints

### ISSUE THREAD

**Issue by hamnox** [cinnamon-bun/earthstar#23]
Attempted to make new db with cli, documentation has a different command than the code btw, but more concerningly I ran into an error: `workspace address does not start with "@"`.

adding a @ does not fix it

in https://github.com/cinnamon-bun/earthstar/blob/master/src/util/addresses.ts:
>     if (!addr.startsWith('//')) {
>         return { workspaceParsed: null, err: 'workspace address does not start with "@"' };
>     }

the error message does not match the test

**Comment by cinnamon-bun** [comment]
Thanks so much for this report!

- Fixed the error message which was a typo
- The README for [earthstar-cli](https://github.com/cinnamon-bun/earthstar-cli) was out of date.  Updated it and added a description of the workspace address format, which looks like `//myworkspace.12345`
- Found and fixed a bug in the `sync` command-line code
- Added test script to catch regressions in the future

Install the new version with
```sh
npm install --global earthstar-cli@latest
```
